# Site settings
title: Jekyll 101 | Notas & Docs sobre Jekyll
description: "Mi aprendizaje sobre Jekyll."
url: "https://dsigno.github.io/notas-mas-docs/"
author:
  name: "dsigno"
  email: "dsigno4all@gmail.com"
  url: "http://www.dsigno.com"

# Build settings
baseurl: /notas-mas-docs # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

plugins:
  - jekyll-paginate
paginate: 5
